import {
  AuditRun,
  BacklinkProfileOverview,
  RankTrackingOverview,
  CompetitorIntelligenceOverview,
  ListingsManagementOverview,
  SocialSchedulingOverview,
  DigitalPrOverview,
  QuotaLedger,
  KeywordExplorerResult,
} from '@rivue/types';

export const SEED_KEYWORD_RESULT: KeywordExplorerResult = {
  seedKeyword: 'crm software',
  overview: {
    id: 'kw_crm_software',
    keyword: 'crm software',
    volume: 165000,
    kdScore: 78,
    cpc: 18.45,
    competition: 0.88,
    intent: 'commercial',
    serpFeatures: ['People Also Ask', 'Knowledge Graph', 'Sitelinks', 'Google Ads', 'Top Stories'],
    trend: [
      { month: 'Sep', volume: 142000 },
      { month: 'Oct', volume: 155000 },
      { month: 'Nov', volume: 160000 },
      { month: 'Dec', volume: 138000 },
      { month: 'Jan', volume: 172000 },
      { month: 'Feb', volume: 168000 },
      { month: 'Mar', volume: 175000 },
      { month: 'Apr', volume: 162000 },
      { month: 'May', volume: 158000 },
      { month: 'Jun', volume: 164000 },
      { month: 'Jul', volume: 169000 },
      { month: 'Aug', volume: 165000 },
    ],
    lastUpdated: 'Today at 01:15 AM',
  },
  suggestions: [
    { keyword: 'best crm software for small business', volume: 33100, kdScore: 42, cpc: 14.2, intent: 'commercial', trendType: 'rising' },
    { keyword: 'free crm software', volume: 49500, kdScore: 56, cpc: 8.9, intent: 'transactional', trendType: 'stable' },
    { keyword: 'cloud based crm software', volume: 12100, kdScore: 38, cpc: 16.5, intent: 'commercial', trendType: 'rising' },
    { keyword: 'crm software open source', volume: 8100, kdScore: 24, cpc: 5.4, intent: 'informational', trendType: 'stable' },
    { keyword: 'real estate crm software', volume: 22200, kdScore: 49, cpc: 19.8, intent: 'commercial', trendType: 'rising' },
    { keyword: 'crm software pricing comparison', volume: 5400, kdScore: 29, cpc: 11.3, intent: 'commercial', trendType: 'rising' },
    { keyword: 'enterprise crm software tools', volume: 6600, kdScore: 68, cpc: 24.5, intent: 'transactional', trendType: 'stable' },
  ],
  questions: [
    { keyword: 'what is crm software used for', volume: 18100, kdScore: 18, cpc: 2.3, intent: 'informational', trendType: 'stable' },
    { keyword: 'how much does crm software cost', volume: 9900, kdScore: 22, cpc: 7.8, intent: 'informational', trendType: 'rising' },
    { keyword: 'which crm software is easiest to learn', volume: 4400, kdScore: 15, cpc: 4.1, intent: 'informational', trendType: 'rising' },
    { keyword: 'is hubspot or salesforce better for startups', volume: 6200, kdScore: 31, cpc: 12.0, intent: 'commercial', trendType: 'stable' },
  ],
};

export const SEED_SITE_AUDIT: AuditRun = {
  id: 'audit_run_latest',
  siteId: 'site_rivue_main',
  targetUrl: 'https://rivue.io',
  healthScore: 88,
  previousScore: 81,
  crawledPagesCount: 148,
  errorsCount: 4,
  warningsCount: 18,
  noticesCount: 32,
  passedChecksCount: 284,
  status: 'completed',
  startedAt: '2026-08-30T22:30:00Z',
  completedAt: '2026-08-30T22:32:15Z',
  coreWebVitals: {
    lcp: { value: 1.8, unit: 's', rating: 'good' },
    inp: { value: 92, unit: 'ms', rating: 'good' },
    cls: { value: 0.04, unit: '', rating: 'good' },
    ttfb: { value: 280, unit: 'ms', rating: 'good' },
    fcp: { value: 1.1, unit: 's', rating: 'good' },
  },
  issues: [
    {
      id: 'iss_404_links',
      code: 'broken_internal_links',
      title: '4 Broken Internal Links Found',
      description: 'Crawled 4 internal links pointing to non-existent 404 pages.',
      severity: 'error',
      category: 'links',
      impact: 'Drains crawl budget and harms user journey and indexation.',
      howToFix: 'Update the href targets or add 301 redirects to valid canonical URLs.',
      affectedUrlsCount: 4,
      sampleUrls: ['https://rivue.io/blog/old-2024-guide', 'https://rivue.io/features/legacy-api'],
    },
    {
      id: 'iss_missing_meta',
      code: 'missing_meta_descriptions',
      title: '12 Pages Missing Meta Description',
      description: 'Search engines are auto-generating snippets from body content.',
      severity: 'warning',
      category: 'onpage',
      impact: 'Lower click-through rates in organic SERP listings.',
      howToFix: 'Add compelling 140–160 character meta descriptions with target keywords.',
      affectedUrlsCount: 12,
      sampleUrls: ['https://rivue.io/pricing/enterprise', 'https://rivue.io/integrations/zapier'],
    },
    {
      id: 'iss_missing_alt',
      code: 'images_missing_alt_tags',
      title: '9 Images Missing Alt Attributes',
      description: 'Images lack descriptive alt tags for accessibility and image search.',
      severity: 'warning',
      category: 'onpage',
      impact: 'Missed ranking in Google Image Search and lower accessibility compliance.',
      howToFix: 'Add descriptive alt text describing the image contents and context.',
      affectedUrlsCount: 9,
      sampleUrls: ['https://rivue.io/assets/dashboard-mockup.png'],
    },
    {
      id: 'iss_schema_notice',
      code: 'missing_breadcrumb_schema',
      title: 'Breadcrumb Structured Data Recommended',
      description: 'Sub-category pages would benefit from BreadcrumbList JSON-LD markup.',
      severity: 'notice',
      category: 'structured_data',
      impact: 'Enables rich breadcrumbs navigation trail in Google search results.',
      howToFix: 'Inject Schema.org BreadcrumbList JSON-LD in the HTML head.',
      affectedUrlsCount: 22,
      sampleUrls: ['https://rivue.io/docs/api/quickstart'],
    },
  ],
};

export const SEED_BACKLINK_OVERVIEW: BacklinkProfileOverview = {
  targetDomain: 'rivue.io',
  domainRating: 64,
  totalBacklinks: 48200,
  referringDomainsCount: 1420,
  dofollowRatio: 78,
  spamScoreAvg: 4,
  velocityHistory: [
    { month: 'Mar', gained: 85, lost: 12, net: 73 },
    { month: 'Apr', gained: 110, lost: 18, net: 92 },
    { month: 'May', gained: 145, lost: 24, net: 121 },
    { month: 'Jun', gained: 190, lost: 30, net: 160 },
    { month: 'Jul', gained: 240, lost: 35, net: 205 },
    { month: 'Aug', gained: 285, lost: 42, net: 243 },
  ],
  recentBacklinks: [
    {
      id: 'bl_1',
      sourceUrl: 'https://techcrunch.com/2026/08/best-seo-innovations',
      sourceTitle: '10 Innovative Growth Platforms Reshaping Organic Marketing',
      targetUrl: 'https://rivue.io',
      anchorText: 'Rivue intelligence platform',
      linkType: 'dofollow',
      domainRating: 92,
      pageAuthority: 74,
      spamScore: 1,
      firstSeen: '2 days ago',
      lastSeen: '6 hours ago',
      isLost: false,
    },
    {
      id: 'bl_2',
      sourceUrl: 'https://searchengineland.com/seo-chrome-extensions-review',
      sourceTitle: 'Must-Have Chrome Extensions for Daily Technical SEO',
      targetUrl: 'https://rivue.io/extension',
      anchorText: 'Rivue Chrome Extension',
      linkType: 'dofollow',
      domainRating: 88,
      pageAuthority: 69,
      spamScore: 2,
      firstSeen: '5 days ago',
      lastSeen: '1 day ago',
      isLost: false,
    },
    {
      id: 'bl_3',
      sourceUrl: 'https://marketingland.io/growth-stack-2026',
      sourceTitle: 'The Modern B2B Growth Stack',
      targetUrl: 'https://rivue.io',
      anchorText: 'https://rivue.io',
      linkType: 'nofollow',
      domainRating: 68,
      pageAuthority: 52,
      spamScore: 3,
      firstSeen: '1 week ago',
      lastSeen: '3 days ago',
      isLost: false,
    },
  ],
  topReferringDomains: [
    { domain: 'techcrunch.com', domainRating: 92, backlinksCount: 8, dofollowCount: 7, firstSeen: '2026-03-12' },
    { domain: 'searchengineland.com', domainRating: 88, backlinksCount: 14, dofollowCount: 12, firstSeen: '2026-02-18' },
    { domain: 'producthunt.com', domainRating: 89, backlinksCount: 42, dofollowCount: 30, firstSeen: '2026-01-05' },
    { domain: 'github.com', domainRating: 96, backlinksCount: 120, dofollowCount: 85, firstSeen: '2025-11-20' },
  ],
  anchorDistributions: [
    { anchorText: 'Rivue', backlinksCount: 18400, domainsCount: 650, percentage: 38.2 },
    { anchorText: 'Rivue Chrome Extension', backlinksCount: 9200, domainsCount: 380, percentage: 19.1 },
    { anchorText: 'https://rivue.io', backlinksCount: 6800, domainsCount: 220, percentage: 14.1 },
    { anchorText: 'seo competitor intelligence', backlinksCount: 4100, domainsCount: 140, percentage: 8.5 },
    { anchorText: 'keyword difficulty checker', backlinksCount: 2900, domainsCount: 95, percentage: 6.0 },
  ],
  prospects: [
    {
      id: 'prosp_1',
      domain: 'hubspot.com',
      contactName: 'Amanda Brooks (Senior Editor)',
      contactEmail: 'abrooks@hubspot.com',
      type: 'guest_post',
      opportunityUrl: 'https://blog.hubspot.com/marketing/write-for-us',
      domainRating: 93,
      status: 'in_progress',
      notes: 'Pitched guest column on unified digital PR & SERP volatility.',
    },
    {
      id: 'prosp_2',
      domain: 'backlinko.com',
      contactName: 'Brian Dean / Editorial Team',
      type: 'broken_link',
      opportunityUrl: 'https://backlinko.com/seo-tools',
      domainRating: 90,
      status: 'discovered',
      notes: 'Broken outbound link on old Mangools guide ready for replacement pitch.',
    },
    {
      id: 'prosp_3',
      domain: 'cxl.com',
      contactName: 'Peep Laja',
      type: 'resource_page',
      opportunityUrl: 'https://cxl.com/blog/growth-tools',
      domainRating: 85,
      status: 'contacted',
      notes: 'Outreach email sent on Aug 28.',
    },
  ],
};

export const SEED_RANK_TRACKING: RankTrackingOverview = {
  totalTracked: 124,
  top3Count: 28,
  top10Count: 64,
  top100Count: 118,
  improvedCount: 34,
  declinedCount: 9,
  unchangedCount: 81,
  averagePosition: 8.4,
  serpVolatilityIndex: 3.4,
  visibilityScore: 78.5,
  keywords: [
    {
      id: 'trk_1',
      keyword: 'competitor intelligence platform',
      currentPosition: 2,
      previousPosition: 4,
      bestPosition: 2,
      searchVolume: 12400,
      location: 'United States',
      device: 'desktop',
      rankingUrl: 'https://rivue.io/competitor-intelligence',
      serpFeatures: ['Featured Snippet', 'People Also Ask'],
      history: [
        { date: '2026-08-25', position: 6 },
        { date: '2026-08-26', position: 5 },
        { date: '2026-08-27', position: 4 },
        { date: '2026-08-28', position: 4 },
        { date: '2026-08-29', position: 3 },
        { date: '2026-08-30', position: 2 },
      ],
      competitorPositions: { 'semrush.com': 1, 'ahrefs.com': 3, 'spyfu.com': 5 },
      tags: ['Core Product', 'High Intent'],
      lastChecked: 'Today at 02:00 AM',
    },
    {
      id: 'trk_2',
      keyword: 'technical seo chrome extension',
      currentPosition: 1,
      previousPosition: 1,
      bestPosition: 1,
      searchVolume: 18100,
      location: 'United States',
      device: 'desktop',
      rankingUrl: 'https://rivue.io/extension',
      serpFeatures: ['Featured Snippet', 'SiteLinks', 'Images'],
      history: [
        { date: '2026-08-25', position: 1 },
        { date: '2026-08-26', position: 1 },
        { date: '2026-08-27', position: 1 },
        { date: '2026-08-28', position: 1 },
        { date: '2026-08-29', position: 1 },
        { date: '2026-08-30', position: 1 },
      ],
      competitorPositions: { 'detailed.com': 2, 'ahrefs.com': 4 },
      tags: ['Chrome Ext', 'Top Winner'],
      lastChecked: 'Today at 02:00 AM',
    },
    {
      id: 'trk_3',
      keyword: 'digital pr outreach crm',
      currentPosition: 4,
      previousPosition: 7,
      bestPosition: 4,
      searchVolume: 6400,
      location: 'United States',
      device: 'desktop',
      rankingUrl: 'https://rivue.io/pr-crm',
      serpFeatures: ['People Also Ask'],
      history: [
        { date: '2026-08-25', position: 9 },
        { date: '2026-08-26', position: 8 },
        { date: '2026-08-27', position: 7 },
        { date: '2026-08-28', position: 6 },
        { date: '2026-08-29', position: 5 },
        { date: '2026-08-30', position: 4 },
      ],
      competitorPositions: { 'buzzstream.com': 1, 'pitchbox.com': 2, 'muckrack.com': 3 },
      tags: ['PR CRM'],
      lastChecked: 'Today at 02:00 AM',
    },
  ],
};

export const SEED_COMPETITOR_OVERVIEW: CompetitorIntelligenceOverview = {
  trackedDomain: 'rivue.io',
  competitors: [
    {
      domain: 'semrush.com',
      name: 'Semrush',
      domainRating: 91,
      estimatedMonthlyTraffic: 14200000,
      organicKeywordsCount: 3800000,
      totalBacklinksCount: 182000000,
      trafficTrendPercentage: 4.2,
      topPages: [
        { url: 'https://semrush.com/features/keyword-magic-tool', estimatedTraffic: 480000, keywordsCount: 4200, topKeyword: 'keyword research' },
        { url: 'https://semrush.com/analytics/backlinks', estimatedTraffic: 310000, keywordsCount: 3100, topKeyword: 'backlink checker' },
      ],
    },
    {
      domain: 'ahrefs.com',
      name: 'Ahrefs',
      domainRating: 90,
      estimatedMonthlyTraffic: 11800000,
      organicKeywordsCount: 2900000,
      totalBacklinksCount: 145000000,
      trafficTrendPercentage: -1.4,
      topPages: [
        { url: 'https://ahrefs.com/site-explorer', estimatedTraffic: 620000, keywordsCount: 5100, topKeyword: 'website authority checker' },
        { url: 'https://ahrefs.com/keywords-explorer', estimatedTraffic: 410000, keywordsCount: 3800, topKeyword: 'keyword difficulty' },
      ],
    },
    {
      domain: 'mangools.com',
      name: 'Mangools',
      domainRating: 77,
      estimatedMonthlyTraffic: 890000,
      organicKeywordsCount: 240000,
      totalBacklinksCount: 4900000,
      trafficTrendPercentage: 8.5,
      topPages: [
        { url: 'https://mangools.com/kwfinder', estimatedTraffic: 220000, keywordsCount: 1800, topKeyword: 'kwfinder' },
      ],
    },
  ],
  keywordGap: [
    { keyword: 'backlink analyzer free', searchVolume: 27100, kdScore: 48, cpc: 8.5, yourPosition: null, competitorPositions: { 'semrush.com': 2, 'ahrefs.com': 1, 'mangools.com': 7 }, gapType: 'missing', opportunityScore: 92 },
    { keyword: 'serp volatility tracker', searchVolume: 8400, kdScore: 28, cpc: 4.2, yourPosition: 6, competitorPositions: { 'semrush.com': 1, 'ahrefs.com': 4, 'mangools.com': 9 }, gapType: 'weak', opportunityScore: 84 },
    { keyword: 'technical seo chrome extension', searchVolume: 18100, kdScore: 35, cpc: 6.8, yourPosition: 1, competitorPositions: { 'semrush.com': 8, 'ahrefs.com': 4, 'mangools.com': 14 }, gapType: 'strong', opportunityScore: 98 },
    { keyword: 'digital pr outreach templates', searchVolume: 5200, kdScore: 22, cpc: 3.1, yourPosition: null, competitorPositions: { 'semrush.com': 5, 'ahrefs.com': null, 'mangools.com': null }, gapType: 'untapped', opportunityScore: 89 },
  ],
  growthFeed: [
    {
      id: 'feed_1',
      domain: 'semrush.com',
      type: 'new_content',
      title: 'Semrush published a new 5,000-word guide on AI Overviews SEO',
      description: 'Targeting keyword "how to rank in google ai overviews" (Vol: 14k, KD: 32).',
      impact: 'high',
      timestamp: '2 hours ago',
    },
    {
      id: 'feed_2',
      domain: 'ahrefs.com',
      type: 'ranking_drop',
      title: 'Ahrefs dropped from #2 to #5 for "free keyword tool"',
      description: 'Lost position to Google Search Console and Rivue.',
      impact: 'medium',
      timestamp: '6 hours ago',
    },
    {
      id: 'feed_3',
      domain: 'mangools.com',
      type: 'new_backlink',
      title: 'Mangools gained a high-authority backlink from Forbes (DR 94)',
      description: 'Featured in "Best SEO Tools for SMBs in Q3 2026".',
      impact: 'high',
      timestamp: '1 day ago',
    },
  ],
};

export const SEED_LISTINGS_OVERVIEW: ListingsManagementOverview = {
  napAudit: {
    canonicalName: 'Rivue Technologies Inc.',
    canonicalAddress: '548 Market St, Suite 39201, San Francisco, CA 94104',
    canonicalPhone: '+1 (415) 890-4820',
    canonicalWebsite: 'https://rivue.io',
    napScore: 94,
    directoriesCount: 4,
    syncedCount: 3,
    issuesCount: 1,
  },
  listings: [
    {
      id: 'list_gbp',
      platform: 'google',
      platformName: 'Google Business Profile',
      status: 'synced',
      publishedName: 'Rivue Technologies Inc.',
      publishedAddress: '548 Market St, Suite 39201, San Francisco, CA 94104',
      publishedPhone: '+1 (415) 890-4820',
      publishedWebsite: 'https://rivue.io',
      rating: 4.9,
      reviewCount: 48,
      lastSyncedAt: 'Today at 00:45 AM',
    },
    {
      id: 'list_bing',
      platform: 'bing',
      platformName: 'Bing Places for Business',
      status: 'synced',
      publishedName: 'Rivue Technologies Inc.',
      publishedAddress: '548 Market St, Suite 39201, San Francisco, CA 94104',
      publishedPhone: '+1 (415) 890-4820',
      publishedWebsite: 'https://rivue.io',
      rating: 4.8,
      reviewCount: 16,
      lastSyncedAt: 'Yesterday',
    },
    {
      id: 'list_apple',
      platform: 'apple',
      platformName: 'Apple Business Connect',
      status: 'synced',
      publishedName: 'Rivue Technologies Inc.',
      publishedAddress: '548 Market St, Suite 39201, San Francisco, CA 94104',
      publishedPhone: '+1 (415) 890-4820',
      publishedWebsite: 'https://rivue.io',
      rating: 5.0,
      reviewCount: 12,
      lastSyncedAt: '2 days ago',
    },
    {
      id: 'list_yelp',
      platform: 'yelp',
      platformName: 'Yelp for Business',
      status: 'discrepancy_detected',
      publishedName: 'Rivue Tech',
      publishedAddress: '548 Market Street, San Francisco, CA 94104',
      publishedPhone: '+1 (415) 890-4820',
      publishedWebsite: 'https://rivue.io',
      rating: 4.6,
      reviewCount: 22,
      lastSyncedAt: '3 days ago',
      discrepancies: ['Business name abbreviated as "Rivue Tech" instead of "Rivue Technologies Inc."', 'Suite 39201 missing in address'],
    },
  ],
  reviews: [
    {
      id: 'rev_1',
      platform: 'google',
      authorName: 'Marcus Vance',
      rating: 5,
      sentiment: 'positive',
      sentimentScore: 0.96,
      comment: 'Rivue completely replaced our separate subscriptions to Ahrefs and Semrush. The Chrome extension gives our editorial team live keyword data right inside CMS.',
      publishedAt: 'Yesterday',
      hasReplied: true,
      replyText: 'Thanks Marcus! So glad the Chrome extension is saving your editorial team hours every week.',
    },
    {
      id: 'rev_2',
      platform: 'google',
      authorName: 'Elena Rostova',
      rating: 5,
      sentiment: 'positive',
      sentimentScore: 0.92,
      comment: 'The digital PR CRM module is super intuitive. Found 5 top tech journalists in under 10 minutes and landed a Tier-1 link.',
      publishedAt: '3 days ago',
      hasReplied: false,
      aiSuggestedReply: 'Thank you Elena! Fantastic to hear our PR discovery helped you land that tier-1 link. Let us know if you need custom email pitch templates!',
    },
    {
      id: 'rev_3',
      platform: 'yelp',
      authorName: 'David K.',
      rating: 3,
      sentiment: 'neutral',
      sentimentScore: 0.52,
      comment: 'Good overall suite but would love faster crawl depth for 10,000+ page e-commerce websites.',
      publishedAt: '1 week ago',
      hasReplied: false,
      aiSuggestedReply: 'Hi David, thank you for the constructive feedback! We have just upgraded our worker crawl cluster for multi-threaded parallel crawling on large enterprise catalogs.',
    },
  ],
  averageRating: 4.84,
  totalReviews: 98,
  responseRatePercentage: 88.5,
  averageResponseTimeHours: 2.4,
};

export const SEED_SOCIAL_OVERVIEW: SocialSchedulingOverview = {
  scheduledCount: 8,
  publishedThisMonth: 42,
  avgEngagementRate: 4.2,
  audienceGrowthRate: 18.5,
  posts: [
    {
      id: 'post_1',
      content: '🚀 Introducing the Rivue Manifest V3 Chrome Extension. Audit any URL, inspect heading hierarchies, and uncover competitor keyword gaps with zero context switching. Free trial live today! 👇',
      platforms: ['x', 'linkedin'],
      status: 'scheduled',
      scheduledFor: '2026-08-31T14:00:00Z',
      author: 'Marketing Team',
    },
    {
      id: 'post_2',
      content: 'Why unlinked brand mentions are the most overlooked goldmine in digital PR in 2026 — and how to turn them into high-DR backlinks in 3 steps: 🧵',
      platforms: ['x', 'linkedin'],
      status: 'published',
      scheduledFor: '2026-08-29T10:00:00Z',
      publishedAt: '2026-08-29T10:01:00Z',
      engagement: { impressions: 14200, likes: 380, comments: 46, shares: 88, clicks: 540 },
      author: 'CEO',
    },
    {
      id: 'post_3',
      content: '5 technical SEO checks you should run before launching any Next.js 15 site: canonical tags, JSON-LD breadcrumbs, Core Web Vitals TTFB, robots.txt, and image alt fallback.',
      platforms: ['linkedin', 'x'],
      status: 'draft',
      scheduledFor: '2026-09-02T09:30:00Z',
      author: 'SEO Lead',
    },
  ],
  competitorSocial: [
    { competitorDomain: 'semrush.com', platform: 'x', handle: '@semrush', followersCount: 245000, postingFrequencyPerWeek: 18, averageEngagementRate: 1.8, growthRateMonthly: 2.1, topPostExample: 'Weekly SEO breakdown webinar' },
    { competitorDomain: 'ahrefs.com', platform: 'x', handle: '@ahrefs', followersCount: 168000, postingFrequencyPerWeek: 12, averageEngagementRate: 2.9, growthRateMonthly: 3.4, topPostExample: 'New search traffic study with 1B pages' },
  ],
  competitorAds: [
    {
      id: 'ad_1',
      competitorDomain: 'semrush.com',
      platform: 'Google / Meta',
      adHeadline: 'Outrank Your Competitors in 2026 | Start Free Trial',
      adBody: 'Discover the exact keywords your rivals are paying for. Access 25B+ keywords and full backlink intelligence.',
      landingPageUrl: 'https://semrush.com/lp/competitor-research',
      firstSeen: '2026-07-15',
      lastActive: 'Active Now',
      mediaType: 'image',
    },
  ],
};

export const SEED_PR_OVERVIEW: DigitalPrOverview = {
  totalJournalists: 340,
  activeCampaignsCount: 3,
  averageReplyRate: 28.4,
  totalBrandMentions: 58,
  unlinkedMentionsCount: 14,
  journalists: [
    {
      id: 'jour_1',
      name: 'Sarah Perez',
      outlet: 'TechCrunch',
      beat: ['SaaS', 'Marketing Tech', 'AI Tools', 'Startups'],
      email: 'sarah.perez@techcrunch.com',
      twitterHandle: '@sarahintampa',
      relevanceScore: 96,
      recentArticleTitle: 'How AI Automation is Transforming Modern Growth Marketing',
      recentArticleUrl: 'https://techcrunch.com/author/sarah-perez',
      pitchStatus: 'replied',
      lastContactedAt: '2026-08-28',
    },
    {
      id: 'jour_2',
      name: 'Barry Schwartz',
      outlet: 'Search Engine Roundtable',
      beat: ['Search Engine Algorithms', 'Google Updates', 'SEO Tools'],
      email: 'barry@rustybrick.com',
      twitterHandle: '@rustybrick',
      relevanceScore: 98,
      recentArticleTitle: 'Google Rollout of Core Algorithm Update Tracking',
      recentArticleUrl: 'https://seroundtable.com',
      pitchStatus: 'published',
      lastContactedAt: '2026-08-25',
    },
    {
      id: 'jour_3',
      name: 'Nicole Fallon',
      outlet: 'Business News Daily / Forbes',
      beat: ['Small Business Tech', 'Productivity Software', 'PR Tools'],
      email: 'nfallon@businessnewsdaily.com',
      relevanceScore: 88,
      recentArticleTitle: 'Best CRM and Outreach Platforms for SMBs',
      pitchStatus: 'pitched',
      lastContactedAt: '2026-08-29',
    },
  ],
  campaigns: [
    {
      id: 'camp_1',
      name: 'Rivue 2026 Manifest V3 Launch Campaign',
      targetTopic: 'Chrome Extensions & Technical SEO',
      status: 'active',
      totalProspects: 45,
      sentCount: 38,
      openRate: 76.3,
      replyRate: 31.5,
      placementsCount: 6,
      emailSubjectTemplate: 'Exclusive: Why next-gen SEO is moving directly into the browser panel',
      emailBodyTemplate: 'Hi {{name}}, saw your recent coverage on {{recent_article}}... we built Rivue to solve the multi-tab fatigue marketers face.',
      createdAt: '2026-08-15',
    },
    {
      id: 'camp_2',
      name: 'Q3 Search Volatility Study & Data Drop',
      targetTopic: 'Google Core Update Data Analysis',
      status: 'active',
      totalProspects: 60,
      sentCount: 52,
      openRate: 82.0,
      replyRate: 26.8,
      placementsCount: 8,
      emailSubjectTemplate: 'Data Drop: Analysis of 500k keywords affected by Google\'s latest update',
      emailBodyTemplate: 'Hi {{name}}, sharing our proprietary dataset analyzing position shifts across 500k SERP snapshots...',
      createdAt: '2026-08-22',
    },
  ],
  mentions: [
    {
      id: 'men_1',
      source: 'TechCrunch',
      sourceDomain: 'techcrunch.com',
      title: 'Rivue Launches Unified SEO, PR & Social Extension for Growth Marketers',
      url: 'https://techcrunch.com/2026/08/rivue-launch-announcement',
      snippet: 'Rivue provides a unified browser side panel combining SERP tracking and technical site health checks.',
      publishedAt: '2 days ago',
      sentiment: 'positive',
      domainRating: 92,
      isLinked: true,
      reachEstimate: 450000,
    },
    {
      id: 'men_2',
      source: 'Search Engine Land',
      sourceDomain: 'searchengineland.com',
      title: 'Top Tools for Monitoring SERP Volatility in 2026',
      url: 'https://searchengineland.com/serp-volatility-tools',
      snippet: 'Notable newcomer Rivue provides real-time volatility alerting directly inside Chrome.',
      publishedAt: '4 days ago',
      sentiment: 'positive',
      domainRating: 88,
      isLinked: false, // Prime opportunity for outreach
      reachEstimate: 220000,
    },
  ],
};

export const SEED_QUOTA_LEDGER: QuotaLedger = {
  organizationId: 'org_rivue_enterprise',
  tier: 'pro',
  monthlyAllowance: 50000,
  creditsRemaining: 34250,
  creditsUsedThisBillingCycle: 15750,
  resetDate: '2026-09-15',
  usageByModule: {
    keyword_search: 6200,
    site_audit: 4500,
    serp_snapshot: 2400,
    backlink_crawl: 1200,
    rank_check: 850,
    pr_enrichment: 400,
    social_publish: 200,
  },
  recentTransactions: [
    {
      id: 'tx_1',
      module: 'keyword_search',
      creditsDeducted: 10,
      balanceAfter: 34250,
      description: 'SERP & Keyword Explorer query: "crm software"',
      timestamp: 'Today at 01:15 AM',
      userId: 'usr_admin',
    },
    {
      id: 'tx_2',
      module: 'site_audit',
      creditsDeducted: 150,
      balanceAfter: 34260,
      description: 'Technical Site Audit run for https://rivue.io (148 pages)',
      timestamp: 'Yesterday at 22:30 PM',
      userId: 'usr_admin',
    },
    {
      id: 'tx_3',
      module: 'rank_check',
      creditsDeducted: 124,
      balanceAfter: 34410,
      description: 'Scheduled daily position check (124 tracked keywords)',
      timestamp: 'Yesterday at 02:00 AM',
      userId: 'usr_system',
    },
  ],
};
