import { GlossaryTerm } from '@rivue/types';

export const GLOSSARY_DICTIONARY: Record<string, GlossaryTerm> = {
  kd_score: {
    id: 'kd_score',
    term: 'Keyword Difficulty (KD)',
    plainEnglishName: 'How easy this keyword is to rank for',
    shortDefinition: 'An estimate from 0 to 100 indicating how hard it will be to rank on page 1 of Google for this query.',
    whyItMatters: 'Targeting lower KD keywords gives your content a much faster path to ranking and driving organic clicks without massive backlink budgets.',
    benchmarkGuide: {
      good: '0 – 25: Easy to rank for with solid content.',
      average: '26 – 50: Moderate competition. Needs a few high-quality backlinks.',
      poor: '51 – 100: Heavy competition dominated by high-authority websites.',
    },
    category: 'keywords',
  },
  search_volume: {
    id: 'search_volume',
    term: 'Search Volume',
    plainEnglishName: 'Monthly Search Interest',
    shortDefinition: 'The estimated number of times people search for this exact term in Google each month.',
    whyItMatters: 'Helps you prioritize keywords with enough audience demand to deliver meaningful organic traffic to your business.',
    benchmarkGuide: {
      good: '1,000+ monthly searches for primary landing pages.',
      average: '200 – 1,000 searches for niche long-tail terms.',
      poor: '<50 searches (very low intent unless highly enterprise).',
    },
    category: 'keywords',
  },
  cpc: {
    id: 'cpc',
    term: 'Cost Per Click (CPC)',
    plainEnglishName: 'Estimated Paid Ad Cost',
    shortDefinition: 'The average amount advertisers pay each time a user clicks their sponsored ad for this keyword on Google Ads.',
    whyItMatters: 'High CPC indicates strong commercial intent — competitors are willing to pay top dollar because visitors convert into revenue.',
    benchmarkGuide: {
      good: '$3.00+ denotes high buyer intent and commercial value.',
      average: '$1.00 – $3.00 standard informational/discovery rate.',
      poor: '<$0.50 usually informational or non-monetized queries.',
    },
    category: 'keywords',
  },
  search_intent: {
    id: 'search_intent',
    term: 'Search Intent',
    plainEnglishName: 'Searcher Purpose',
    shortDefinition: 'The underlying goal behind a user\'s query: Informational, Commercial, Transactional, or Navigational.',
    whyItMatters: 'Google ranks pages that match the user\'s exact stage in their journey. Mismatching intent leads to high bounce rates.',
    benchmarkGuide: {
      good: 'Transactional & Commercial intent convert best for sales.',
      average: 'Informational intent builds brand awareness and top-of-funnel reach.',
      poor: 'Navigational is only helpful if they are searching for your brand.',
    },
    category: 'keywords',
  },
  serp_features: {
    id: 'serp_features',
    term: 'SERP Features',
    plainEnglishName: 'Special Search Widgets',
    shortDefinition: 'Visual elements on Google search results beyond standard blue links (e.g. People Also Ask, Featured Snippets, Local Packs, Video Carousels).',
    whyItMatters: 'Rich features capture user attention before standard results. Optimizing for snippets can catapult your brand to position zero.',
    benchmarkGuide: {
      good: 'Featured Snippet & PAA: Excellent opportunities to win position 0.',
      average: 'Knowledge Graph: Good for brand credibility.',
      poor: 'Heavy Ad Packs: Lowers standard organic click-through rates.',
    },
    category: 'keywords',
  },
  domain_rating: {
    id: 'domain_rating',
    term: 'Domain Rating (DR)',
    plainEnglishName: 'Website Authority Score',
    shortDefinition: 'A proprietary 0–100 logarithmic metric measuring the overall strength and authority of a website\'s backlink profile.',
    whyItMatters: 'Higher DR sites naturally rank faster and higher for competitive terms because search engines trust their authority.',
    benchmarkGuide: {
      good: 'DR 60+ (Established industry leader / powerhouse).',
      average: 'DR 30 – 59 (Growing authority with healthy backlink base).',
      poor: 'DR 0 – 29 (Newer or low-authority site requiring link acquisition).',
    },
    category: 'backlinks',
  },
  referring_domains: {
    id: 'referring_domains',
    term: 'Referring Domains',
    plainEnglishName: 'Unique Websites Linking to You',
    shortDefinition: 'The total number of distinct websites that contain at least one backlink pointing to your domain.',
    whyItMatters: 'Search engines value 100 links from 100 different websites far more than 10,000 links from a single site.',
    benchmarkGuide: {
      good: '100+ unique high-authority referring domains.',
      average: '25 – 100 unique referring domains.',
      poor: '<10 referring domains (insufficient backlink diversity).',
    },
    category: 'backlinks',
  },
  anchor_text: {
    id: 'anchor_text',
    term: 'Anchor Text',
    plainEnglishName: 'Clickable Link Text',
    shortDefinition: 'The visible, clickable text within a hyperlink pointing to your webpage.',
    whyItMatters: 'Helps search engines understand the topic of the destination page. A natural distribution prevents Google over-optimization penalties.',
    benchmarkGuide: {
      good: 'A balanced mix of Brand (50%), Exact Match (15%), and Natural URL/Generic (35%).',
      average: 'High brand anchor percentage.',
      poor: '>40% exact commercial match anchors (triggers spam flags).',
    },
    category: 'backlinks',
  },
  dofollow_ratio: {
    id: 'dofollow_ratio',
    term: 'Dofollow vs Nofollow Ratio',
    plainEnglishName: 'Authority-Passing Link Share',
    shortDefinition: 'The percentage of your incoming backlinks that pass PageRank / search authority ("dofollow") versus those marked "nofollow" or "sponsored".',
    whyItMatters: 'Dofollow links directly elevate your ranking authority, but a 100% dofollow profile looks artificial. A healthy natural blend is key.',
    benchmarkGuide: {
      good: '65% – 85% Dofollow (natural, authoritative profile).',
      average: '50% – 64% Dofollow.',
      poor: '<30% (weak authority pass) or >95% (unnatural footprint).',
    },
    category: 'backlinks',
  },
  spam_score: {
    id: 'spam_score',
    term: 'Backlink Spam Score',
    plainEnglishName: 'Toxic Link Risk',
    shortDefinition: 'A 0–100% rating of how many toxic, low-quality, or manipulative link patterns are detected in your backlink profile.',
    whyItMatters: 'High spam scores put your domain at risk of algorithmic suppression or manual action from Google.',
    benchmarkGuide: {
      good: '1% – 30%: Clean and low risk.',
      average: '31% – 60%: Moderate risk. Requires backlink audit & disavow.',
      poor: '61% – 100%: High risk of algorithmic penalty.',
    },
    category: 'backlinks',
  },
  site_health: {
    id: 'site_health',
    term: 'Site Health Score',
    plainEnglishName: 'Technical Website Health',
    shortDefinition: 'An overall 0–100 score reflecting technical SEO hygiene, crawlability, mobile responsiveness, and page performance.',
    whyItMatters: 'Technical errors (broken links, redirect loops, missing canonicals) silently drain your crawl budget and harm rankings.',
    benchmarkGuide: {
      good: '85 – 100 (Clean site with no major crawl blockers).',
      average: '70 – 84 (Some warnings or minor crawl issues to resolve).',
      poor: '<70 (Critical technical errors harming search visibility).',
    },
    category: 'site_audit',
  },
  core_web_vitals: {
    id: 'core_web_vitals',
    term: 'Core Web Vitals (CWV)',
    plainEnglishName: 'Speed & User Experience Metrics',
    shortDefinition: 'Google\'s standardized metrics for measuring real-world user experience: Largest Contentful Paint (LCP), Interaction to Next Paint (INP), and Cumulative Layout Shift (CLS).',
    whyItMatters: 'CWV is a confirmed Google ranking factor and directly impacts user conversion and bounce rates.',
    benchmarkGuide: {
      good: 'LCP < 2.5s, INP < 200ms, CLS < 0.1 (Passes Google standards).',
      average: 'LCP 2.5s–4.0s, INP 200–500ms, CLS 0.1–0.25 (Needs Work).',
      poor: 'LCP > 4.0s or CLS > 0.25 (Poor user experience).',
    },
    category: 'site_audit',
  },
  canonical_tag: {
    id: 'canonical_tag',
    term: 'Canonical Tag',
    plainEnglishName: 'Master Page Declaration',
    shortDefinition: 'An HTML link element (`rel="canonical"`) telling search engines which version of a duplicate or similar URL is the authoritative master.',
    whyItMatters: 'Prevents duplicate content penalties and consolidates ranking signals to a single preferred URL.',
    benchmarkGuide: {
      good: 'Self-referencing canonical on all unique pages.',
      average: 'Pointing parameter URLs to clean root URLs.',
      poor: 'Missing or circular canonical tags causing index confusion.',
    },
    category: 'site_audit',
  },
  hreflang: {
    id: 'hreflang',
    term: 'Hreflang Tags',
    plainEnglishName: 'Language & Region Signals',
    shortDefinition: 'Code tags that specify the language and geographical targeting of a webpage for multi-lingual and international websites.',
    whyItMatters: 'Ensures Google serves the Spanish version to users in Spain and the English version to users in the US without duplicate penalties.',
    benchmarkGuide: {
      good: 'Bidirectional return tags configured for all localized versions.',
      average: 'Configured on main landing pages.',
      poor: 'Missing return tags or incorrect ISO language/country codes.',
    },
    category: 'site_audit',
  },
  nap_consistency: {
    id: 'nap_consistency',
    term: 'NAP Consistency',
    plainEnglishName: 'Name, Address & Phone Accuracy',
    shortDefinition: 'The percentage match of your business Name, Address, and Phone Number across all online business directories (Google, Bing, Apple Maps, Yelp).',
    whyItMatters: 'Consistent NAP data is the #1 ranking factor for Google Local Map Pack results. Mismatched details confuse search engines and customers.',
    benchmarkGuide: {
      good: '95% – 100%: Perfect directory synchronization.',
      average: '80% – 94%: Minor formatting or suite number discrepancies.',
      poor: '<80%: Critical phone/address conflicts hurting local rankings.',
    },
    category: 'listings',
  },
  sentiment_score: {
    id: 'sentiment_score',
    term: 'Sentiment Score',
    plainEnglishName: 'Customer Sentiment Rating',
    shortDefinition: 'An AI-powered classification of review tone measuring the ratio of positive vs negative feedback across all customer touchpoints.',
    whyItMatters: 'High sentiment scores boost local conversion rates and signal customer satisfaction to search engines.',
    benchmarkGuide: {
      good: '0.80+ (Overwhelmingly positive reviews & testimonials).',
      average: '0.50 – 0.79 (Balanced feedback with room for service improvement).',
      poor: '<0.50 (Frequent negative reviews requiring urgent PR resolution).',
    },
    category: 'listings',
  },
  engagement_rate: {
    id: 'engagement_rate',
    term: 'Social Engagement Rate',
    plainEnglishName: 'Audience Interaction Rate',
    shortDefinition: 'The percentage of your social followers or viewers who interact (like, comment, repost, click) with your published posts.',
    whyItMatters: 'High engagement signals algorithmic quality, leading social platforms to push your organic posts to wider viral feeds.',
    benchmarkGuide: {
      good: '3.5%+ on LinkedIn / Instagram is top tier.',
      average: '1.0% – 3.4% standard B2B / B2C engagement.',
      poor: '<0.8% indicates low content resonance or inactive followers.',
    },
    category: 'social',
  },
  content_gap: {
    id: 'content_gap',
    term: 'Content Gap',
    plainEnglishName: 'Missing Keyword Opportunities',
    shortDefinition: 'Topics, sub-headings, and keywords that your top competitors rank for on page 1, but your website completely lacks.',
    whyItMatters: 'Exposes immediate, high-converting content topics ready for your team to write and capture market share.',
    benchmarkGuide: {
      good: 'Targeting high-volume, low-KD content gap keywords.',
      average: 'Covering secondary sub-topics on existing landing pages.',
      poor: 'Ignoring competitor content advantages.',
    },
    category: 'competitors',
  },
  serp_volatility: {
    id: 'serp_volatility',
    term: 'SERP Volatility Index',
    plainEnglishName: 'Algorithm Turbulence Level',
    shortDefinition: 'A 0–10 index measuring how aggressively search engine ranking positions are fluctuating across your tracked keywords.',
    whyItMatters: 'High volatility alerts you to ongoing Google core algorithm updates, competitor campaigns, or indexing turbulence.',
    benchmarkGuide: {
      good: '0.0 – 3.5: Calm waters, stable ranking landscape.',
      average: '3.6 – 6.5: Normal daily fluctuations.',
      poor: '6.6 – 10.0: High turbulence / major Google algorithm rollout in progress.',
    },
    category: 'rank_tracking',
  },
  organic_ctr: {
    id: 'organic_ctr',
    term: 'Estimated Organic CTR',
    plainEnglishName: 'Click-Through Rate from Search',
    shortDefinition: 'The estimated percentage of searchers who will click on your result based on your exact organic ranking position and SERP features.',
    whyItMatters: 'Ranking #1 captures ~28% of all searches, while position #10 captures only ~2%. Moving up just two spots can double traffic.',
    benchmarkGuide: {
      good: '20%+ (Position #1 or #2 organic ranking).',
      average: '6% – 15% (Positions #3 to #5).',
      poor: '<3% (Positions #7 to #10 or bottom of page 1).',
    },
    category: 'keywords',
  },
  link_velocity: {
    id: 'link_velocity',
    term: 'Link Velocity',
    plainEnglishName: 'New Backlink Growth Rate',
    shortDefinition: 'The speed at which a website is acquiring new backlinks over a 30-day or 90-day window.',
    whyItMatters: 'Consistent, steady link growth signals a thriving, relevant brand. Sudden unnatural spikes or severe link loss alert search engines.',
    benchmarkGuide: {
      good: '+15 to +50 new referring domains monthly (natural, steady growth).',
      average: '+2 to +14 new domains monthly.',
      poor: 'Negative net link velocity (losing more links than gaining).',
    },
    category: 'backlinks',
  },
  media_mentions: {
    id: 'media_mentions',
    term: 'Media Mentions',
    plainEnglishName: 'Press & Editorial Coverage',
    shortDefinition: 'Tracked citations of your company, brand, or executive names across news outlets, podcasts, and digital media publications.',
    whyItMatters: 'Brand mentions build immense authority and provide prime opportunities to reach out for high-value editorial backlinks.',
    benchmarkGuide: {
      good: '5+ tier-1 news / trade press mentions per quarter.',
      average: '1–4 brand citations per month.',
      poor: '0 brand awareness in industry press.',
    },
    category: 'pr_crm',
  },
};

export function getGlossaryTerm(termKey: string): GlossaryTerm | undefined {
  return GLOSSARY_DICTIONARY[termKey];
}
